export const siteContent = {
  metadata: {
    title: "Sreeram — Portfolio",
    description: "CS student and builder, CCE Kerala. Software, embedded systems, and projects.",
  },
  name: "Sreeram",
  role: "CS student and builder, CCE Kerala",
  location: "Kerala, India",
  orientation: { title: "Explore in portrait", hint: "Rotate your device" },
  navigation: {
    label: "Navigation",
    menu: "Menu",
    close: "Close menu",
    connections: "Connections",
    coordinates: ["[latitude]", "[longitude]"],
    home: { label: "Sreeram", href: "#identity" },
    links: [
      { label: "About", href: "#identity" },
      { label: "Work", href: "#projects" },
      { label: "Contact", href: "#contact" },
    ],
  },
  sections: {
    identity: {
      id: "identity",
      eyebrow: "Identity hero",
      title: "Sreeram",
      description: "CS student and builder, CCE Kerala",
      displayLines: ["SREE", "RAM"],
      badge: "CS student and builder",
      region: "IN",
      locationLabel: "Kerala, India",
      scrollLabel: "Scroll to explore",
    },
    manifesto: {
      id: "manifesto",
      eyebrow: "Manifesto",
      title: "Learning by building",
      displayWords: ["Learning", "by", "building"],
      description: "Exploring software and embedded systems through hands-on projects.",
    },
    statistics: {
      id: "statistics",
      eyebrow: "Statistics and tools",
      title: "In progress",
      description: "[Add personal statistics and tools here]",
      counters: [
        { label: "[Projects]", value: "5" },
        { label: "[Experience]", value: "—" },
        { label: "[Milestones]", value: "—" },
      ],
      tools: ["[Tool 01]", "[Tool 02]", "[Tool 03]", "[Tool 04]"],
    },
    projects: {
      id: "projects",
      eyebrow: "Project showcase",
      title: "Selected projects",
      description: "Software, telemetry, and embedded systems.",
      cardTag: "[Project]",
      viewLabel: "[View]",
      moreWork: { label: "[More work]", href: "#" },
    },
    experience: {
      id: "experience",
      eyebrow: "Experience",
      title: "Learning and building",
      description: "[Add experience and milestones here]",
      expandMark: "+",
      collapseMark: "−",
      entries: [
        { id: "experience-01", index: "01", title: "[Experience 01]", role: "[Role]", description: "[Add experience or milestone here]" },
        { id: "experience-02", index: "02", title: "[Experience 02]", role: "[Role]", description: "[Add experience or milestone here]" },
        { id: "experience-03", index: "03", title: "[Experience 03]", role: "[Role]", description: "[Add experience or milestone here]" },
        { id: "experience-04", index: "04", title: "[Experience 04]", role: "[Role]", description: "[Add experience or milestone here]" },
        { id: "experience-05", index: "05", title: "[Experience 05]", role: "[Role]", description: "[Add experience or milestone here]" },
        { id: "experience-06", index: "06", title: "[Experience 06]", role: "[Role]", description: "[Add experience or milestone here]" },
        { id: "experience-07", index: "07", title: "[Experience 07]", role: "[Role]", description: "[Add experience or milestone here]" },
      ],
    },
  },
  projects: [
    { id: "thuzhayan", title: "Thuzhayan", description: "AI-instrumented Vallamkali telemetry", href: "#" },
    { id: "saferoad", title: "SafeRoad", description: "ESP32 + Firebase road safety", href: "#" },
    { id: "dual-drone", title: "AICTE dual-drone disaster rescue system", description: "Dual-drone disaster rescue system", href: "#" },
    { id: "cce-judge", title: "CCE Judge", description: "Competitive programming platform", href: "#" },
    { id: "weather-station", title: "Weather Station Dashboard", description: "Weather station dashboard", href: "#" },
  ],
  footer: {
    id: "contact",
    eyebrow: "Contact footer",
    title: "Let’s connect",
    groupLabels: ["Contact", "Connections", "Location"],
    locationHref: "#",
    message: { label: "[email]", href: "#" },
    cv: { label: "[CV]", href: "#" },
    links: [
      { label: "[GitHub]", href: "#" },
      { label: "[LinkedIn]", href: "#" },
    ],
  },
} as const;

export type SectionContent = (typeof siteContent.sections)[keyof typeof siteContent.sections];
