export const siteContent = {
  metadata: {
    title: "Sreeram — Portfolio",
    description: "CS student and builder, CCE Kerala. Software, embedded systems, and projects.",
  },
  name: "Sreeram",
  role: "CS student and builder, CCE Kerala",
  location: "Kerala, India",
  orientation: { title: "Explore in portrait", hint: "Rotate your device" },
  navigation: {
    label: "Navigation",
    menu: "Menu",
    close: "Close menu",
    connections: "Connections",
    coordinates: ["TODO: latitude", "TODO: longitude"],
    home: { label: "Sreeram", href: "#identity" },
    links: [
      { label: "About", href: "#identity" },
      { label: "Work", href: "#projects" },
      { label: "Contact", href: "#contact" },
    ],
  },
  sections: {
    identity: {
      id: "identity",
      eyebrow: "Identity hero",
      title: "Sreeram",
      description: "CS student and builder, CCE Kerala",
      displayLines: ["SREE", "RAM"],
      badge: "CS student and builder",
      region: "IN",
      locationLabel: "Kerala, India",
      scrollLabel: "Scroll to explore",
    },
    manifesto: {
      id: "manifesto",
      eyebrow: "Manifesto",
      title: "Learning by building",
      displayWords: ["Learning", "by", "building"],
      description: "Exploring software and embedded systems through hands-on projects.",
    },
    statistics: {
      id: "statistics",
      eyebrow: "Statistics and tools",
      title: "In progress",
      description: "TODO: provide confirmed statistics and tools.",
      counters: [
        { label: "Projects - TODO", value: "—" },
        { label: "Experience - TODO", value: "—" },
        { label: "Milestones - TODO", value: "—" },
      ],
      tools: ["TODO: tool", "TODO: tool 2", "TODO: tool 3", "TODO: tool 4"],
    },
    projects: {
      id: "projects",
      eyebrow: "Project showcase",
      title: "Selected projects",
      description: "Software, telemetry, and embedded systems.",
      cardTag: "Project",
      viewLabel: "View - TODO",
      moreWork: { label: "GitHub - TODO", href: "#contact" },
    },
    experience: {
      id: "experience",
      eyebrow: "Education",
      title: "Learning and building",
      description: "CS student and builder, CCE Kerala",
      expandMark: "+",
      collapseMark: "−",
      entries: [
        { id: "cce-kerala", index: "01", title: "CCE Kerala", role: "CS student", description: "CS student and builder, CCE Kerala." },
      ],
    },
  },
  projects: [
    { id: "thuzhayan", title: "Thuzhayan", description: "AI-instrumented Vallamkali telemetry", href: "#contact", image: null, todo: "TODO: project link and own image" },
    { id: "saferoad", title: "SafeRoad", description: "ESP32 + Firebase road safety", href: "#contact", image: null, todo: "TODO: project link and own image" },
    { id: "dual-drone", title: "AICTE dual-drone disaster rescue system", description: "Dual-drone disaster rescue system", href: "#contact", image: null, todo: "TODO: project link and own image" },
    { id: "cce-judge", title: "CCE Judge", description: "Competitive programming platform", href: "#contact", image: null, todo: "TODO: project link and own image" },
    { id: "weather-station", title: "Weather Station Dashboard", description: "Weather station dashboard", href: "#contact", image: null, todo: "TODO: project link and own image" },
  ],
  todos: [
    "TODO: email, GitHub and LinkedIn URLs",
    "TODO: project URLs and own project images",
    "TODO: confirmed statistics and tools",
    "TODO: CV file, deployment domain and optional coordinates",
  ],
  footer: {
    id: "contact",
    eyebrow: "Contact footer",
    title: "Let’s connect",
    groupLabels: ["Contact", "Connections", "Location"],
    locationHref: "#contact",
    message: { label: "Email - TODO", href: "#contact" },
    cv: { label: "CV - TODO", href: "#contact" },
    links: [
      { label: "GitHub - TODO", href: "#contact" },
      { label: "LinkedIn - TODO", href: "#contact" },
    ],
  },
} as const;

export type SectionContent = (typeof siteContent.sections)[keyof typeof siteContent.sections];
